# Generated by Django 5.2 on 2025-04-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Avis", "verbose_name_plural": "Avis"},
        ),
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={
                "verbose_name": "Dossier médical",
                "verbose_name_plural": "Dossiers médicaux",
            },
        ),
        migrations.AlterModelOptions(
            name="reminder",
            options={"verbose_name": "Rappel", "verbose_name_plural": "Rappels"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="datetime",
            field=models.DateTimeField(verbose_name="Date et heure"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médecin",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="mode",
            field=models.CharField(
                choices=[("video", "Vidéo"), ("chat", "Chat")],
                max_length=10,
                verbose_name="Mode de consultation",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("pending", "En attente"), ("done", "Effectué")],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médecin",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="diagnosis",
            field=models.TextField(verbose_name="Diagnostic"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="records/",
                verbose_name="Fichier médical",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatment",
            field=models.TextField(verbose_name="Traitement"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date_time",
            field=models.DateTimeField(verbose_name="Date et heure"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="message",
            field=models.CharField(max_length=255, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="Médecin"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_patient",
            field=models.BooleanField(default=False, verbose_name="Patient"),
        ),
    ]
